[cmod]
MDSPLUS_CONNECTION_STRING = "alcdata-archives"

[cmod.database]
profile_path= "~/logbook.sybase_login"
driver= "ODBC Driver 18 for SQL Server"
host= "alcdb2"
port= 1433
db_name= "logbook"
protected_columns = [
    "time_until_disrupt",
    "ip_error",
    "dip_dt",
    "beta_p",
    "beta_n",
    "li",
    "n_equal_1_normalized",
    "z_error",
    "v_z",
    "z_times_v_z",
    "kappa",
    "pressure_peaking",
    "h98",
    "q0",
    "qstar",
    "q95",
    "dn_dt",
    "p_rad_slow",
    "p_oh_slow",
    "p_icrf",
    "p_lh",
    "radiated_fraction",
    "power_supply_railed",
    "v_loop_efit",
    "lower_gap",
    "upper_gap",
    "dbetap_dt",
    "dli_dt",
    "ip",
    "zcur",
    "n_e",
    "dipprog_dt",
    "v_loop",
    "p_rad",
    "p_oh",
    "ssep",
    "dwmhd_dt",
    "dprad_dt",
    "te_width",
    "greenwald_fraction",
    "intentional_disruption",
    "te_width_ece",
    "wmhd",
    "n_over_ncrit",
    "n_equal_1_mode",
    "mirnov",
    "mirnov_norm_btor",
    "mirnov_norm_bpol",
    "te_peaking",
    "ne_peaking",
    "te_peaking_ece",
    "sxr_peaking",
    "kappa_area",
    "i_efc",
    "sxr",
    "h_alpha",
    "prad_peaking_cva",
    "commit_hash",
]

[cmod.testing]
TEST_COLUMNS=[
	"i_efc",
	"sxr",
	"time_until_disrupt",
	"beta_n",
	"beta_p",
	"kappa",
	"li",
	"upper_gap",
	"lower_gap",
	"q0",
	"qstar",
	"q95",
	"v_loop_efit",
	"wmhd",
	"ssep",
	"n_over_ncrit",
	"dbetap_dt",
	"dli_dt",
	"dwmhd_dt",
	"kappa_area",
	"te_width",
	"ne_peaking",
	"te_peaking",
	"pressure_peaking",
	"n_e",
	"dn_dt",
	"greenwald_fraction",
	"n_equal_1_mode",
	"n_equal_1_normalized",
	"v_0",
	"ip",
	"dip_dt",
	"dipprog_dt",
	"ip_error",
	"z_error",
	"zcur",
	"v_z",
	"z_times_v_z",
	"p_oh",
	"v_loop",
	"p_rad",
	"dprad_dt",
	"p_lh",
	"p_icrf",
	"radiated_fraction",
	"time",
	"shot",
]
EXPECTED_FAILURE_COLUMNS= [
	"te_width",
	"zcur",
	"v_z",
	"z_times_v_z",
	"sxr",
	"ne_peaking",
	"te_peaking",
	"pressure_peaking",
	"greenwald_fraction",
]

[cmod.testing.test_shots]
flattop1_fast = 1150805012
no_disrup1_full = 1150805013
no_disrup2_full = 1150805014
rampdown1_full = 1150805015
rampdown2_full = 1150805016
rampdown3_full = 1150805017
rampdown4_full = 1150805019
rampdown5_full = 1150805020
rampdown6_full = 1150805021
flattop2_full = 1150805022