[cmod.inout.mds]
mdsplus_connection_string = "alcdata-archives"

[cmod.inout.sql]
db_name = "logbook"
driver = "ODBC"
host = "alcdb2"
port = 1433
protected_columns = [
  "beta_n",
  "beta_p",
  "dbetap_dt",
  "dip_dt",
  "dipprog_dt",
  "dli_dt",
  "dn_dt",
  "dprad_dt",
  "dwmhd_dt",
  "greenwald_fraction",
  "h98",
  "h_alpha",
  "i_efc",
  "intentional_disruption",
  "ip",
  "ip_error",
  "kappa",
  "kappa_area",
  "li",
  "lower_gap",
  "mirnov",
  "mirnov_norm_bpol",
  "mirnov_norm_btor",
  "n_e",
  "n_equal_1_mode",
  "n_equal_1_normalized",
  "n_over_ncrit",
  "ne_peaking",
  "p_icrf",
  "p_lh",
  "p_oh",
  "p_oh_slow",
  "p_rad",
  "p_rad_slow",
  "power_supply_railed",
  "prad_peaking_cva",
  "pressure_peaking",
  "q0",
  "q95",
  "qstar",
  "radiated_fraction",
  "ssep",
  "sxr",
  "sxr_peaking",
  "te_peaking",
  "te_peaking_ece",
  "te_width",
  "te_width_ece",
  "time_until_disrupt",
  "upper_gap",
  "v_loop",
  "v_loop_efit",
  "v_z",
  "wmhd",
  "z_error",
  "z_times_v_z",
  "zcur",
]

[cmod.tests]
expected_failure_columns = [
  "greenwald_fraction",
  "ne_peaking",
  "p_oh",
  "pressure_peaking",
  "radiated_fraction",
  "sxr",
  "te_peaking",
  "te_width",
  "v_loop",
  "v_z",
  "z_times_v_z",
  "zcur",
]
test_columns = [
  "beta_n",
  "beta_p",
  "dbetap_dt",
  "dip_dt",
  "dipprog_dt",
  "dli_dt",
  "dn_dt",
  "dprad_dt",
  "dwmhd_dt",
  "greenwald_fraction",
  "i_efc",
  "ip",
  "ip_error",
  "kappa",
  "kappa_area",
  "li",
  "lower_gap",
  "n_e",
  "n_equal_1_mode",
  "n_equal_1_normalized",
  "n_over_ncrit",
  "ne_peaking",
  "p_icrf",
  "p_lh",
  "p_oh",
  "p_rad",
  "pressure_peaking",
  "q0",
  "q95",
  "qstar",
  "radiated_fraction",
  "shot",
  "ssep",
  "sxr",
  "te_peaking",
  "te_width",
  "time",
  "time_until_disrupt",
  "upper_gap",
  "v_loop",
  "v_loop_efit",
  "v_z",
  "wmhd",
  "z_error",
  "z_times_v_z",
  "zcur",
]

[cmod.tests.shots]
flattop1_fast = 1150805012
flattop2_full = 1150805022
no_disrup1_full = 1150805013
no_disrup2_full = 1150805014
rampdown1_full = 1150805015
rampdown2_full = 1150805016
rampdown3_full = 1150805017
rampdown4_full = 1150805019
rampdown5_full = 1150805020
rampdown6_full = 1150805021
