[d3d.inout.mds]
mdsplus_connection_string = "atlas"

[d3d.inout.sql]
db_name = "d3drdb"
driver = "FreeTDS"
host = "d3drdb"
port = 8001
protected_columns = []

[d3d.tests]
expected_failure_columns = [
  "aminor",
  "beta_n",
  "beta_p",
  "beta_p_rt",
  "dbetap_dt",
  "delta",
  "dli_dt",
  "dn_dt",
  "dwmhd_dt",
  "greenwald_fraction",
  "h_alpha",
  "kappa",
  "kappa_area",
  "li",
  "li_rt",
  "lower_gap",
  "n_e",
  "n_equal_1_mode",
  "n_equal_1_normalized",
  "ne_peaking_cva_rt",
  "p_ohm",
  "p_rad",
  "prad_peaking_cva_rt",
  "prad_peaking_xdiv_rt",
  "q0",
  "q95",
  "q95_rt",
  "qstar",
  "radiated_fraction",
  "squareness",
  "te_peaking_cva_rt",
  "upper_gap",
  "wmhd",
  "zcur",
  "zcur_normalized",
]
test_columns = [
  "aminor",
  "beta_n",
  "beta_p",
  "beta_p_rt",
  "dbetap_dt",
  "delta",
  "dip_dt",
  "dipprog_dt",
  "dipprog_dt_rt",
  "dli_dt",
  "dn_dt",
  "dwmhd_dt",
  "greenwald_fraction",
  "greenwald_fraction_rt",
  "h98",
  "h_alpha",
  "ip",
  "ip_error",
  "ip_error_rt",
  "ip_rt",
  "kappa",
  "kappa_area",
  "li",
  "li_rt",
  "lower_gap",
  "n1rms_normalized",
  "n_e",
  "n_e_rt",
  "n_equal_1_mode",
  "n_equal_1_normalized",
  "ne_peaking_cva_rt",
  "p_ech",
  "p_nbi",
  "p_ohm",
  "p_rad",
  "power_supply_railed",
  "prad_peaking_cva_rt",
  "prad_peaking_xdiv_rt",
  "q0",
  "q95",
  "q95_rt",
  "qstar",
  "radiated_fraction",
  "shot",
  "squareness",
  "te_peaking_cva_rt",
  "time",
  "time_until_disrupt",
  "upper_gap",
  "v_loop",
  "wmhd",
  "wmhd_rt",
  "zcur",
  "zcur_normalized",
]

[d3d.tests.shots]
disrup1_fast = 161228
disrup2_full = 161237
no_disrup1_full = 166177
no_disrup2_full = 166253
